const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],E=window.LumaEngine;
const uid=()=>globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`;
const num=(v,d=0)=>Number.isFinite(+v)?+v:d;
const CATALOG_KEY='luma-catalog-v2',RECOVERY_KEY='luma-catalog-v2-recovery',BACKUP_KEY='luma-catalog-v2-last-good',LEGACY_KEY='luma-library',WATERMARK_KEY='luma-watermark-history',TUTORIAL_KEY='luma-first-run-tutorial-v1';
const MAX_CATALOG_BYTES=24_000_000,MAX_CATALOG_PHOTOS=50_000,MAX_BACKUP_BYTES=750_000,MAX_HISTORY_PHOTOS=24,MAX_HISTORY_ENTRIES=50,MAX_HISTORY_ENTRY_BYTES=750_000,MAX_CLEANUP_SPOTS=200,IMAGE_LOAD_TIMEOUT=30_000,PREFETCH_RADIUS=2,MAX_PREFETCH_IMAGES=4,MAX_FILMSTRIP_THUMBS=201,LIBRARY_PAGE_SIZE=400;
let photos=[],current=null,sourceImage=new Image(),view='edit',compare=false,clipping=false,renderQueued=false,renderGeneration=0,imageLoadToken=0,saveTimer=null,catalogDirty=false,catalogGeneration=0,lastSaveErrorAt=0,lastErrorToastAt=0,activeFilter='all',mixerColor='orange',gradingTarget='shadows',curveChannel='rgb',toolMode='',activePreset=null,presetBase=null,batchPresetMode=false,metadataPhoto=null,metadataRating=0,tutorialStep=0,tutorialTarget=null,tutorialReturnFocus=null,helpReturnFocus=null,libraryRenderLimit=LIBRARY_PAGE_SIZE;
const undoByPhoto=new Map(),redoByPhoto=new Map();
const historyLru=new Map(),prefetchCache=new Map();

const sliderPanels={
  Light:[['light.exposure','Exposure',-5,5,.01],['light.contrast','Contrast',-100,100,1],['light.highlights','Highlights',-100,100,1],['light.shadows','Shadows',-100,100,1],['light.whites','Whites',-100,100,1],['light.blacks','Blacks',-100,100,1]],
  Effects:[['effects.texture','Texture',-100,100,1],['effects.clarity','Clarity',-100,100,1],['effects.dehaze','Dehaze',-100,100,1],['effects.vignette','Vignette',-100,100,1],['effects.vignetteMidpoint','Midpoint',0,100,1],['effects.vignetteRoundness','Roundness',-100,100,1],['effects.vignetteFeather','Feather',0,100,1],['effects.vignetteHighlights','Highlights',0,100,1],['effects.grain','Grain',0,100,1],['effects.grainSize','Size',0,100,1],['effects.grainRoughness','Roughness',0,100,1]],
  Detail:[['detail.sharpening','Sharpening',0,150,1],['detail.radius','Radius',.5,3,.1],['detail.sharpenDetail','Detail',0,100,1],['detail.sharpenMasking','Masking',0,100,1],['detail.noiseLuminance','Luminance NR',0,100,1],['detail.noiseDetail','Luminance detail',0,100,1],['detail.noiseContrast','Luminance contrast',0,100,1],['detail.noiseColor','Color NR',0,100,1],['detail.colorDetail','Color detail',0,100,1],['detail.colorSmoothness','Smoothness',0,100,1]],
  Geometry:[['geometry.straighten','Straighten',-45,45,.1],['geometry.distortion','Distortion',-100,100,1],['geometry.vertical','Vertical',-100,100,1],['geometry.horizontal','Horizontal',-100,100,1],['geometry.rotate','Rotate',-45,45,.1],['geometry.aspect','Aspect',-100,100,1],['geometry.scale','Scale',50,150,1],['geometry.xOffset','X offset',-100,100,1],['geometry.yOffset','Y offset',-100,100,1],['geometry.cropZoom','Crop zoom',100,300,1],['geometry.cropX','Crop X',-100,100,1],['geometry.cropY','Crop Y',-100,100,1]]
};

const presets=[
 {name:'Clean Natural',group:'Color',source:'Luma',style:'linear-gradient(135deg,#a7b0b2,#394245)',patch:{light:{contrast:8,highlights:-20,shadows:20,whites:8,blacks:-8},color:{vibrance:10}}},
 {name:'Natural Portrait',group:'Portrait',source:'Kleinheinz recipe',style:'linear-gradient(135deg,#d8b09e,#805e61)',patch:{light:{highlights:-60,shadows:40,whites:20,blacks:-15,contrast:15},color:{vibrance:15},mixer:{orange:{luminance:15},aqua:{saturation:-25}},grading:{highlights:{hue:45,saturation:8}},curve:{rgb:[[0,8],[64,58],[128,128],[192,198],[255,255]]}}},
 {name:'Warm Portrait Film',group:'Portrait',source:'Editing Studio recipe',style:'linear-gradient(135deg,#dfad7c,#765754)',patch:{light:{highlights:-30,whites:-15,shadows:-10},effects:{clarity:-12,texture:-5,grain:16,grainSize:24,grainRoughness:50},mixer:{orange:{saturation:-18,luminance:12},red:{saturation:-10,luminance:6},green:{hue:6,saturation:-18},yellow:{saturation:-10},blue:{saturation:-12}},grading:{highlights:{hue:44,saturation:8},midtones:{hue:42,saturation:2},shadows:{hue:30,saturation:4},blending:55},curve:{rgb:[[0,18],[65,58],[188,202],[255,222]]}}},
 {name:'Bright & Airy',group:'Portrait',source:'Kleinheinz recipe',style:'linear-gradient(135deg,#f2e5d0,#94b8c2)',patch:{light:{highlights:-40,shadows:70,whites:60,blacks:40,contrast:-10},color:{vibrance:-10,saturation:5},mixer:{yellow:{luminance:20},orange:{luminance:10},blue:{saturation:-30}},grading:{highlights:{hue:60,saturation:5}},curve:{rgb:[[0,20],[64,80],[128,140],[192,200],[255,248]]}}},
 {name:'Moody Landscape',group:'Landscape',source:'Kleinheinz recipe',style:'linear-gradient(135deg,#536c55,#152d3b)',patch:{light:{highlights:-85,shadows:25,whites:-30,blacks:25,contrast:30},color:{vibrance:25,saturation:10},mixer:{blue:{saturation:20},orange:{saturation:15},green:{hue:-15}},grading:{shadows:{hue:220,saturation:12}},curve:{rgb:[[0,18],[55,40],[128,128],[200,218],[255,250]]}}},
 {name:'Landscape Pop',group:'Landscape',source:'Luma',style:'linear-gradient(135deg,#70a85a,#2d75a8)',patch:{light:{contrast:18,highlights:-35,shadows:28,whites:14,blacks:-16},color:{vibrance:26,saturation:4},effects:{texture:18,clarity:12,dehaze:12},mixer:{green:{saturation:12,luminance:5},blue:{saturation:18,luminance:-8}}}},
 {name:'Teal–Amber Cinema',group:'Cinematic',source:'Pixel Bubble recipe',style:'linear-gradient(135deg,#276a72,#d1844e)',patch:{light:{highlights:-45,shadows:35,whites:-12,blacks:18},mixer:{orange:{luminance:15},aqua:{saturation:-12},blue:{saturation:-12},green:{hue:-15}},grading:{shadows:{hue:210,saturation:20},highlights:{hue:40,saturation:15},blending:50,balance:0},effects:{vignette:-15,grain:20,grainSize:25,grainRoughness:50},detail:{sharpening:35,radius:1,sharpenDetail:25},curve:{rgb:[[0,32],[64,54],[128,128],[192,206],[255,242]]}}},
 {name:'Reverse Cinema',group:'Cinematic',source:'Editing Studio range',style:'linear-gradient(135deg,#b17043,#3b637f)',patch:{light:{contrast:18,highlights:-40,shadows:15,whites:-20,blacks:-4},color:{vibrance:-18,saturation:-8},grading:{shadows:{hue:30,saturation:24},highlights:{hue:210,saturation:12},blending:55},effects:{grain:18,grainSize:27,grainRoughness:46},curve:{rgb:[[0,9],[64,52],[128,128],[200,205],[255,245]]}}},
 {name:'Vintage Color Film',group:'Film',source:'Kleinheinz recipe',style:'linear-gradient(135deg,#b79b6c,#4b6b70)',patch:{light:{highlights:-50,shadows:30,whites:-20,blacks:35,contrast:5},color:{vibrance:-15,saturation:10},mixer:{red:{saturation:20},yellow:{saturation:15},blue:{saturation:-20}},grading:{highlights:{hue:35,saturation:15},shadows:{hue:180,saturation:10}},effects:{grain:22,grainSize:26,grainRoughness:48},curve:{rgb:[[0,20],[64,58],[128,128],[192,198],[255,245]]}}},
 {name:'Pastel Color Film',group:'Film',source:'Baker-Green recipe',style:'linear-gradient(135deg,#c6aa9f,#758b9c)',patch:{light:{highlights:-50,shadows:50,whites:-40,blacks:33},effects:{clarity:-10,grain:32,grainSize:25,grainRoughness:50},mixer:{red:{hue:-1},orange:{hue:6,saturation:-23},yellow:{hue:58,saturation:2,luminance:-33},green:{hue:1,saturation:-32},blue:{saturation:-62},purple:{saturation:-66},magenta:{saturation:-66}},grading:{midtones:{hue:217,saturation:28}},curve:{rgb:[[0,0],[60,40],[195,195],[255,255]]}}},
 {name:'Film Matte',group:'Vintage',source:'Layered matte study',style:'linear-gradient(135deg,#938b76,#48505b)',patch:{light:{contrast:-8,highlights:-25,shadows:32,blacks:30},color:{vibrance:-18,saturation:-5},effects:{grain:28,grainSize:30,grainRoughness:58},curve:{rgb:[[0,24],[45,42],[128,130],[210,218],[255,246]]},grading:{shadows:{hue:205,saturation:8},highlights:{hue:45,saturation:10}}}},
 {name:'Golden Ember',group:'Vintage',source:'Warm split-tone study',style:'linear-gradient(135deg,#df9a44,#6b4336)',patch:{color:{temperature:20,tint:5,vibrance:8},light:{highlights:-24,shadows:18},grading:{shadows:{hue:28,saturation:10},midtones:{hue:35,saturation:10},highlights:{hue:48,saturation:18}},mixer:{yellow:{hue:-8},orange:{saturation:8}},effects:{vignette:-10,grain:14}}},
 {name:'Classic B&W',group:'B&W',source:'Kleinheinz recipe',style:'linear-gradient(135deg,#bbb,#222)',patch:{bw:true,light:{highlights:-70,shadows:40,whites:30,blacks:-20,contrast:25},grading:{highlights:{hue:45,saturation:8},shadows:{hue:220,saturation:5}},curve:{rgb:[[0,0],[64,48],[128,128],[192,210],[255,255]]}}},
 {name:'Silver Contrast',group:'B&W',source:'Luma',style:'linear-gradient(135deg,#e0e0e0,#111)',patch:{bw:true,light:{contrast:35,highlights:-35,shadows:18,whites:24,blacks:-28},effects:{clarity:15,grain:18,grainSize:22,grainRoughness:45},curve:{rgb:[[0,0],[58,42],[128,128],[198,218],[255,255]]}}},
 {name:'HDR Natural',group:'HDR',source:'Balanced tone study',style:'linear-gradient(135deg,#6ca5ba,#806c48)',patch:{light:{exposure:.2,highlights:-50,shadows:50,whites:12,blacks:-12,contrast:8},color:{vibrance:14},effects:{texture:12,clarity:9,dehaze:8},detail:{sharpening:28}}},
 {name:'HDR Dramatic',group:'HDR',source:'Luma',style:'linear-gradient(135deg,#287f9f,#d76f3e)',patch:{light:{highlights:-78,shadows:72,whites:25,blacks:-28,contrast:28},color:{vibrance:32,saturation:8},effects:{texture:32,clarity:35,dehaze:24,vignette:-15},detail:{sharpening:48},curve:{rgb:[[0,0],[50,35],[128,132],[205,228],[255,255]]}}}
];

function getPath(obj,path){return path.split('.').reduce((o,k)=>o?.[k],obj)}
function setPath(obj,path,value){const bits=path.split('.');if(bits.some(k=>!k||['__proto__','prototype','constructor'].includes(k)))throw new Error('Invalid setting path');let o=obj;for(let i=0;i<bits.length-1;i++){if(!o[bits[i]]||typeof o[bits[i]]!=='object')o[bits[i]]={};o=o[bits[i]]}o[bits.at(-1)]=value}
function fmt(v){v=+v;if(!Number.isInteger(v))return(v>0?'+':'')+v.toFixed(2);return(v>0?'+':'')+v}
function safeText(s){const d=document.createElement('div');d.textContent=String(s??'');return d.innerHTML}
function safeAttr(s){return safeText(s).replace(/"/g,'&quot;').replace(/'/g,'&#39;')}
function toast(s){const t=$('#toast');if(!t)return; t.textContent=s;t.classList.add('show');clearTimeout(t.timer);t.timer=setTimeout(()=>t.classList.remove('show'),3200)}
function dismissToast(){const t=$('#toast');if(!t)return;clearTimeout(t.timer);t.classList.remove('show')}
const tutorialSteps=[
  {target:'.brand',title:'Welcome to Luma Darkroom',copy:'Luma keeps edits non-destructive: the catalog stores your settings while every original photograph stays untouched.',hint:'This tour takes about one minute.'},
  {target:'#importBtn',title:'Bring in your photographs',copy:'Choose Import photos or drag supported image and camera RAW files anywhere into the window.',hint:'Your files remain in their current folders; Luma remembers their locations.'},
  {target:'.tab[data-view="library"]',prepare:()=>setView('library'),title:'Organize in the Library',copy:'Use Library to search, rate, flag, compare, batch-select, analyze quality, and merge photographs.',hint:'Double-click a thumbnail to open it in Develop.'},
  {target:()=>current?'#adjustPanel':'.tab[data-view="edit"]',prepare:()=>{setView('edit');if(current)switchRightPanel('edit')},title:'Develop with precise controls',copy:'Develop contains Light, Color, Curves, Color Mixer, Effects, Detail, Optics, Geometry, presets, and local masks.',hint:current?'The right panel updates the preview as you edit.':'Import a photo and the full adjustment panel will appear on the right.'},
  {target:'#compareBtn',title:'Check your work and export',copy:'Hold Before or the backslash key to compare with the original. Undo and redo are always available, then Export when the photograph is ready.',hint:'Exports create a new file; they never replace the original.'},
  {target:'#helpBtn',title:'Help is always close',copy:'Open this Help Center at any time for the tutorial, keyboard shortcuts, the user guide, privacy details, and open-source notices.',hint:'Press F1 from anywhere in Luma Darkroom.'}
];
function writeTutorialState(value){try{localStorage.setItem(TUTORIAL_KEY,value)}catch(error){console.warn('[Luma] Could not remember tutorial state',error)}}
function hasSeenTutorial(){try{return!!localStorage.getItem(TUTORIAL_KEY)}catch{return false}}
function clearTutorialTarget(){if(tutorialTarget)tutorialTarget.classList.remove('tutorial-target');tutorialTarget=null}
function tutorialElement(step=tutorialSteps[tutorialStep]){
  const selector=typeof step?.target==='function'?step.target():step?.target,element=selector?$(selector):null;
  if(!element)return null;const style=getComputedStyle(element),rect=element.getBoundingClientRect();return style.display==='none'||style.visibility==='hidden'||rect.width<1||rect.height<1?null:element
}
function placeTutorial(){
  const dialog=$('#tutorialDialog');if(!dialog?.open)return;const target=tutorialTarget,viewportWidth=window.innerWidth,viewportHeight=window.innerHeight,pad=12,gap=14,width=dialog.offsetWidth,height=dialog.offsetHeight;
  if(!target){dialog.style.left=`${Math.max(pad,(viewportWidth-width)/2)}px`;dialog.style.top=`${Math.max(pad,(viewportHeight-height)/2)}px`;return}
  const rect=target.getBoundingClientRect(),clamp=(value,min,max)=>Math.max(min,Math.min(max,value)),alignY=clamp(rect.top,pad,Math.max(pad,viewportHeight-height-pad)),alignX=clamp(rect.left,pad,Math.max(pad,viewportWidth-width-pad));
  const candidates=[{left:rect.right+gap,top:alignY},{left:rect.left-width-gap,top:alignY},{left:alignX,top:rect.bottom+gap},{left:alignX,top:rect.top-height-gap}],fits=point=>point.left>=pad&&point.top>=pad&&point.left+width<=viewportWidth-pad&&point.top+height<=viewportHeight-pad,choice=candidates.find(fits)||{left:clamp((viewportWidth-width)/2,pad,Math.max(pad,viewportWidth-width-pad)),top:clamp((viewportHeight-height)/2,pad,Math.max(pad,viewportHeight-height-pad))};
  dialog.style.left=`${Math.round(choice.left)}px`;dialog.style.top=`${Math.round(choice.top)}px`
}
function renderTutorialStep({focus=true}={}){
  const step=tutorialSteps[tutorialStep];if(!step)return;step.prepare?.();clearTutorialTarget();tutorialTarget=tutorialElement(step);tutorialTarget?.classList.add('tutorial-target');
  $('#tutorialStepLabel').textContent=`STEP ${tutorialStep+1} OF ${tutorialSteps.length}`;$('#tutorialTitle').textContent=step.title;$('#tutorialCopy').textContent=step.copy;$('#tutorialHint').textContent=step.hint||'';$('#tutorialBack').disabled=tutorialStep===0;$('#tutorialNext').textContent=tutorialStep===tutorialSteps.length-1?'Finish':'Next';
  const progress=$('#tutorialProgress');progress.replaceChildren(...tutorialSteps.map((_item,index)=>{const marker=document.createElement('i');marker.className=index<tutorialStep?'complete':index===tutorialStep?'current':'';return marker}));
  requestAnimationFrame(()=>{placeTutorial();if(focus)$('#tutorialNext').focus()})
}
function finishTutorial(state='complete'){
  const dialog=$('#tutorialDialog');writeTutorialState(state);clearTutorialTarget();document.body.classList.remove('tutorial-active');if(dialog?.open)dialog.close(state);const returnTo=tutorialReturnFocus;tutorialReturnFocus=null;requestAnimationFrame(()=>{if(returnTo?.isConnected&&!returnTo.closest('dialog:not([open])'))returnTo.focus();else $('#helpBtn')?.focus()})
}
function startTutorial(){
  const dialog=$('#tutorialDialog');if(!dialog)return;$$('dialog[open]').forEach(openDialog=>{if(openDialog!==dialog)openDialog.close()});tutorialReturnFocus=$('#helpBtn');tutorialStep=0;document.body.classList.add('tutorial-active');if(!dialog.open)dialog.showModal();renderTutorialStep()
}
function openHelpCenter(){
  const dialog=$('#helpDialog');if(!dialog)return;if($('#tutorialDialog')?.open)finishTutorial('skipped');$$('dialog[open]').forEach(openDialog=>{if(openDialog!==dialog)openDialog.close()});if(dialog.open){$('#startTutorialBtn').focus();return}helpReturnFocus=document.activeElement;dialog.showModal();requestAnimationFrame(()=>$('#startTutorialBtn').focus())
}
async function openHelpGuide(){
  const status=$('#guideStatus'),button=$('#openGuideBtn');status.classList.remove('hidden');status.textContent='Opening the guide…';button.disabled=true;
  try{
    const result=await window.desktop?.openHelpGuide?.();
    if(result?.opened)status.textContent='The installation and user guide opened in your browser.';
    else if(result?.reason==='not-configured')status.textContent='The online guide is not published in this build yet. The tutorial and shortcuts above remain available offline.';
    else status.textContent='The guide could not be opened securely. Please use the in-app tutorial for now.'
  }catch(error){console.warn('[Luma] Open help guide',error);status.textContent='The guide could not be opened. Please use the in-app tutorial for now.'}
  finally{button.disabled=false}
}
function scheduleFirstRunTutorial(){if(hasSeenTutorial())return;setTimeout(()=>{if(!document.querySelector('dialog[open]'))startTutorial()},450)}
function reportFailure(context,error,message='Something went wrong. Your catalog and edits are still available.'){
  console.error(`[Luma] ${context}`,error);const now=Date.now();if(now-lastErrorToastAt>3500){lastErrorToastAt=now;toast(message)}
}
function runAsync(context,task,message){return Promise.resolve().then(task).catch(error=>reportFailure(context,error,message))}
function checksum(text){let h=2166136261;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(16)}
function isBackupCandidate(raw){try{const data=JSON.parse(raw),list=Array.isArray(data)?data:data?.photos;return Array.isArray(list)&&list.length<=MAX_CATALOG_PHOTOS&&(!data?.checksum||checksum(JSON.stringify(list))===data.checksum)}catch{return false}}
function catalogRecords(){return photos.map(p=>({id:p.id,filePath:p.filePath,name:p.name,edits:p.edits,rating:p.rating,flag:p.flag,label:p.label,tags:p.tags,caption:p.caption,quality:p.quality,importedAt:p.importedAt}))}
function makeCatalogPayload(){const records=catalogRecords(),body=JSON.stringify(records);if(body.length>MAX_CATALOG_BYTES)throw new RangeError('The catalog is too large for local storage.');const savedAt=Date.now();catalogGeneration=Math.max(catalogGeneration+1,savedAt);return JSON.stringify({app:'Luma Darkroom',version:2,savedAt,generation:catalogGeneration,checksum:checksum(body),photos:records})}
function storageGet(key){try{return localStorage.getItem(key)}catch(error){reportFailure('Read catalog storage',error,'Catalog storage is unavailable. Back up your catalog before closing.');return null}}
function storageRemove(key){try{localStorage.removeItem(key)}catch(error){console.warn(`[Luma] Could not remove ${key}`,error)}}
function watermarkHistory(){try{const list=JSON.parse(storageGet(WATERMARK_KEY)||'[]');return Array.isArray(list)?list.filter(v=>typeof v==='string'&&v.trim()).map(v=>v.trim().slice(0,80)).slice(0,3):[]}catch{return[]}}
function refreshWatermarkHistory(){const list=$('#watermarkHistory');if(!list)return;list.replaceChildren(...watermarkHistory().map(value=>{const option=document.createElement('option');option.value=value;return option}))}
function rememberWatermark(value){value=String(value||'').trim().slice(0,80);if(!value)return;const next=[value,...watermarkHistory().filter(item=>item!==value)].slice(0,3);try{localStorage.setItem(WATERMARK_KEY,JSON.stringify(next));refreshWatermarkHistory()}catch(error){console.warn('[Luma] Could not remember watermark',error)}}
function isQuotaError(error){return error?.name==='QuotaExceededError'||error?.code===22||error?.code===1014}
function saveCatalog({silent=false}={}){
  clearTimeout(saveTimer);saveTimer=null;let payload;
  try{payload=makeCatalogPayload()}catch(error){catalogDirty=true;reportFailure('Serialize catalog',error,'Catalog could not be autosaved. Export a catalog backup before closing.');return false}
  const previous=storageGet(CATALOG_KEY);let recoveryWritten=false;
  try{
    if(previous&&previous.length<=MAX_BACKUP_BYTES&&isBackupCandidate(previous))try{localStorage.setItem(BACKUP_KEY,previous)}catch{}
    try{localStorage.setItem(RECOVERY_KEY,payload);recoveryWritten=true}catch(error){if(!isQuotaError(error))throw error;storageRemove(RECOVERY_KEY)}
    try{localStorage.setItem(CATALOG_KEY,payload)}catch(firstError){
      if(!isQuotaError(firstError))throw firstError;storageRemove(BACKUP_KEY);
      try{localStorage.setItem(CATALOG_KEY,payload)}catch(secondError){if(recoveryWritten){storageRemove(RECOVERY_KEY);recoveryWritten=false;localStorage.setItem(CATALOG_KEY,payload)}else throw secondError}
    }
    storageRemove(RECOVERY_KEY);catalogDirty=false;return true;
  }catch(error){
    catalogDirty=true;const now=Date.now();if(!silent&&now-lastSaveErrorAt>10_000){lastSaveErrorAt=now;reportFailure('Save catalog',error,isQuotaError(error)?'Catalog storage is full. Save a catalog backup before closing.':'Catalog autosave failed. Save a catalog backup before closing.')}return false;
  }
}
function debounceSave(){catalogDirty=true;clearTimeout(saveTimer);saveTimer=setTimeout(()=>saveCatalog(),300)}
function flushCatalog(){if(catalogDirty)saveCatalog({silent:true})}
function touchHistory(id){if(!id)return;historyLru.delete(id);historyLru.set(id,Date.now());while(historyLru.size>MAX_HISTORY_PHOTOS){const oldest=historyLru.keys().next().value;historyLru.delete(oldest);undoByPhoto.delete(oldest);redoByPhoto.delete(oldest)}}
function historyStacks(){const id=current?.id;if(!id)return[[],[]];touchHistory(id);if(!undoByPhoto.has(id))undoByPhoto.set(id,[]);if(!redoByPhoto.has(id))redoByPhoto.set(id,[]);return[undoByPhoto.get(id),redoByPhoto.get(id)]}
function pushHistory(before,after,label='Edit'){
  if(!current)return;let beforeJson,afterJson;try{beforeJson=JSON.stringify(before);afterJson=JSON.stringify(after)}catch(error){reportFailure('Capture edit history',error,'This edit was applied, but could not be added to undo history.');return}
  if(beforeJson===afterJson)return;if(beforeJson.length+afterJson.length>MAX_HISTORY_ENTRY_BYTES){toast('Edit applied · undo history skipped for this large change');return}
  const[u,r]=historyStacks();u.push({before:JSON.parse(beforeJson),after:JSON.parse(afterJson),label:String(label).slice(0,100)});if(u.length>MAX_HISTORY_ENTRIES)u.splice(0,u.length-MAX_HISTORY_ENTRIES);r.length=0;updateUndoButtons()
}
function pushBulkHistory(changes,label='Batch edit'){
  if(!current||!changes.length)return false;let json;try{json=JSON.stringify(changes.map(change=>({id:change.id,before:change.before,after:change.after})))}catch(error){reportFailure('Capture batch history',error,'The batch edit was not applied because its undo record could not be created.');return false}
  if(json.length>MAX_HISTORY_ENTRY_BYTES){toast('Select fewer photographs so this batch can remain undoable');return false}const[u,r]=historyStacks();u.push({bulk:JSON.parse(json),label:String(label).slice(0,100)});if(u.length>MAX_HISTORY_ENTRIES)u.splice(0,u.length-MAX_HISTORY_ENTRIES);r.length=0;updateUndoButtons();return true
}
function applyHistoryItem(item,state){if(item.bulk){for(const change of item.bulk){const photo=photos.find(candidate=>candidate.id===change.id);if(photo)photo.edits=E.clone(change[state])}}else if(current)current.edits=E.clone(item[state])}
function clearPresetTracking(){activePreset=null;presetBase=null}
function updateUndoButtons(){if(!current){$('#undoBtn').disabled=$('#redoBtn').disabled=true;return}const[u,r]=historyStacks();$('#undoBtn').disabled=!u.length;$('#redoBtn').disabled=!r.length}
function commit(label,fn){if(!current)return;clearPresetTracking();let before;try{before=E.clone(current.edits);fn();current.edits=E.migratedEdits(current.edits)}catch(error){if(before)current.edits=before;reportFailure(`Apply ${label}`,error,'That edit could not be applied; the previous settings were restored.');refreshControls();scheduleRender();return}pushHistory(before,current.edits,label);refreshControls();scheduleRender();debounceSave()}

function controlId(path){return`control-${path.replace(/[^a-z0-9]+/gi,'-').toLowerCase()}`}
function range(path,label,min,max,step=1,extra=''){const id=controlId(path);return`<div class="control ${extra}"><label for="${id}">${label}<output data-out="${path}" for="${id}">0</output></label><input id="${id}" aria-label="${label}" data-path="${path}" type="range" min="${min}" max="${max}" step="${step}" value="0"></div>`}
function panel(name,body,open=true){const id=`panel-${name.replace(/[^a-z0-9]+/gi,'-').toLowerCase()}`,bodyId=`${id}-body`;return`<section class="panel ${open?'':'collapsed'}" data-panel-name="${name}"><div class="panel-title-row"><button class="panel-head" aria-expanded="${open}" aria-controls="${bodyId}">${name}</button><button class="reset-one" aria-label="Reset ${name}">reset</button></div><div class="panel-body" id="${bodyId}">${body}</div></section>`}

function buildAdjustments(){
  const profile=`<div class="select-control"><label for="profileSelect">Profile</label><select id="profileSelect" data-select-path="profile"><option>Luma Color</option><option>Luma Vivid</option><option>Luma Neutral</option><option>Luma Portrait</option><option>Luma Landscape</option><option>Monochrome</option></select></div>${range('profileAmount','Amount',0,200,1)}<label class="check-row">Black & white<input type="checkbox" data-check-path="bw"></label>`;
  const light=`<div class="auto-row"><button id="autoTone">Auto</button><button id="clipToggle" aria-pressed="false">Clipping</button><button id="toneReset">Reset tone</button></div>${sliderPanels.Light.map(x=>range(...x)).join('')}`;
  const curve=`<div class="curve-toolbar" aria-label="Tone curve channel">${['rgb','red','green','blue'].map(c=>`<button data-curve-channel="${c}" aria-pressed="false">${c.toUpperCase()}</button>`).join('')}</div><div class="curve-wrap"><canvas id="curveCanvas" width="300" height="165" role="img" aria-label="Tone curve editor; use presets below for a keyboard alternative"></canvas></div><div class="button-row"><button data-curve-preset="linear">Linear</button><button data-curve-preset="medium">Medium</button><button data-curve-preset="strong">Strong</button></div>${range('curve.refineSaturation','Refine saturation',-100,100,1)}<div class="curve-help">Click to add · drag to adjust · double-click a point to remove</div>`;
  const color=`<div class="select-control"><label for="whiteBalanceSelect">White balance</label><select id="whiteBalanceSelect" data-select-path="color.wb"><option>As Shot</option><option>Auto</option><option>Daylight</option><option>Cloudy</option><option>Shade</option><option>Tungsten</option><option>Fluorescent</option><option>Flash</option></select></div>${range('color.temperature','Temperature',-100,100,1)}${range('color.tint','Tint',-100,100,1)}${range('color.vibrance','Vibrance',-100,100,1)}${range('color.saturation','Saturation',-100,100,1)}`;
  const mixer=`<div class="mixer-colors" aria-label="Color mixer range">${E.COLORS.map(c=>`<button class="color-chip" data-color="${c}" title="${c}" aria-label="${c} color range" aria-pressed="false"></button>`).join('')}</div><div id="mixerSliders"></div><button id="mixerPicker" class="mini-btn">⌖ Target HSL range</button><div class="subhead">POINT COLOR</div><label class="check-row">Enable point color<input type="checkbox" data-check-path="pointColor.enabled"></label><div class="point-swatch" id="pointSwatch"></div>${range('pointColor.hueShift','Hue shift',-100,100,1)}${range('pointColor.saturationShift','Saturation shift',-100,100,1)}${range('pointColor.luminanceShift','Luminance shift',-100,100,1)}${range('pointColor.variance','Variance',0,100,1)}${range('pointColor.range','Range',1,100,1)}<label class="check-row">Visualize range<input type="checkbox" data-check-path="pointColor.visualize"></label><button id="pointColorPicker" class="mini-btn">⌖ Pick point color</button>`;
  const grading=`<div class="grading-tabs" aria-label="Color grading range">${['shadows','midtones','highlights','global'].map(c=>`<button data-grade="${c}" aria-label="${c} grading" aria-pressed="false">${c[0].toUpperCase()}</button>`).join('')}</div><div id="gradingSliders"></div>${range('grading.blending','Blending',0,100,1)}${range('grading.balance','Balance',-100,100,1)}`;
  const optics=`<label class="check-row">Remove chromatic aberration<input type="checkbox" data-check-path="optics.removeCA"></label><label class="check-row">Enable lens corrections<input type="checkbox" data-check-path="optics.lensCorrections"></label>${range('optics.distortion','Lens distortion',-100,100,1)}${range('optics.lensVignette','Lens vignetting',-100,100,1)}${range('optics.defringePurple','Purple defringe',0,100,1)}${range('optics.defringeGreen','Green defringe',0,100,1)}`;
  const geometry=`<div class="select-control"><label for="cropAspectSelect">Crop aspect</label><select id="cropAspectSelect" data-select-path="geometry.cropAspect"><option>Original</option><option>Square</option><option>4 × 5</option><option>5 × 4</option><option>2 × 3</option><option>3 × 2</option><option>9 × 16</option><option>16 × 9</option></select></div><div class="button-row"><button data-upright="auto">Reset upright</button><button data-upright="level">Reset level</button><button data-upright="full">Reset full</button></div>${sliderPanels.Geometry.map(x=>range(...x)).join('')}<label class="check-row">Constrain crop<input type="checkbox" data-check-path="geometry.constrainCrop"></label>`;
  $('#adjustments').innerHTML=panel('Profile',profile)+panel('Light',light)+panel('Tone Curve',curve)+panel('Color',color)+panel('Color Mixer',mixer)+panel('Color Grading',grading)+panel('Effects',sliderPanels.Effects.map(x=>range(...x)).join(''),false)+panel('Detail',sliderPanels.Detail.map(x=>range(...x)).join(''),false)+panel('Optics',optics,false)+panel('Crop & Geometry',geometry,false);
  buildMixerSliders();buildGradingSliders();bindAdjustmentEvents();drawCurve();
}
function buildMixerSliders(){$('#mixerSliders').innerHTML=['hue','saturation','luminance'].map(k=>range(`mixer.${mixerColor}.${k}`,k[0].toUpperCase()+k.slice(1),-100,100,1)).join('');bindRanges($('#mixerSliders'));$$('.color-chip').forEach(b=>{const active=b.dataset.color===mixerColor;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))});refreshControls()}
function buildGradingSliders(){$('#gradingSliders').innerHTML=range(`grading.${gradingTarget}.hue`,'Hue',0,360,1,'gradient-hue')+range(`grading.${gradingTarget}.saturation`,'Saturation',0,100,1)+range(`grading.${gradingTarget}.luminance`,'Luminance',-100,100,1);bindRanges($('#gradingSliders'));$$('[data-grade]').forEach(b=>{const active=b.dataset.grade===gradingTarget;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))});refreshControls()}
function bindRanges(root=document){root.querySelectorAll('input[data-path]').forEach(el=>{let before=null,photoId=null;const begin=()=>{if(!current)return false;clearPresetTracking();if(!before||photoId!==current.id){before=E.clone(current.edits);photoId=current.id}return true},finish=()=>{if(before&&current?.id===photoId)pushHistory(before,current.edits,el.dataset.path);before=null;photoId=null};el.onpointerdown=begin;el.oninput=()=>{if(!begin())return;setPath(current.edits,el.dataset.path,+el.value);const out=document.querySelector(`[data-out="${el.dataset.path}"]`);if(out)out.value=fmt(el.value);scheduleRender();debounceSave()};el.onchange=finish;el.onblur=finish;el.onpointercancel=finish})}
function bindAdjustmentEvents(){
  bindRanges($('#adjustments'));
  $$('.panel-head').forEach(b=>b.onclick=()=>{const panel=b.closest('.panel'),collapsed=panel.classList.toggle('collapsed');b.setAttribute('aria-expanded',String(!collapsed));if(panel.dataset.panelName==='Tone Curve')drawCurve()});
  $$('.reset-one').forEach(b=>b.onclick=e=>{e.stopPropagation();resetPanel(b.closest('.panel').dataset.panelName)});
  $$('[data-select-path]').forEach(el=>el.onchange=()=>commit(el.dataset.selectPath,()=>{setPath(current.edits,el.dataset.selectPath,el.value);if(el.dataset.selectPath==='color.wb')applyWB(el.value)}));
  $$('[data-check-path]').forEach(el=>el.onchange=()=>commit(el.dataset.checkPath,()=>setPath(current.edits,el.dataset.checkPath,el.checked)));
  $$('.color-chip').forEach(b=>b.onclick=()=>{mixerColor=b.dataset.color;buildMixerSliders()});
  $$('[data-grade]').forEach(b=>b.onclick=()=>{gradingTarget=b.dataset.grade;buildGradingSliders()});
  $$('[data-curve-channel]').forEach(b=>b.onclick=()=>{curveChannel=b.dataset.curveChannel;drawCurve()});
  $$('[data-curve-preset]').forEach(b=>b.onclick=()=>commit('Curve preset',()=>{const pts={linear:[[0,0],[255,255]],medium:[[0,0],[64,52],[128,128],[192,204],[255,255]],strong:[[0,0],[55,35],[128,128],[205,230],[255,255]]}[b.dataset.curvePreset];current.edits.curve[curveChannel]=pts}));
  $('#autoTone').onclick=autoTone;$('#toneReset').onclick=()=>resetPanel('Light');$('#clipToggle').onclick=()=>{clipping=!clipping;$('#clipToggle').classList.toggle('active',clipping);$('#clipToggle').setAttribute('aria-pressed',String(clipping));scheduleRender()};$('#mixerPicker').onclick=()=>setTool('color');$('#pointColorPicker').onclick=()=>setTool('point');
  $$('[data-upright]').forEach(b=>b.onclick=()=>commit('Upright',()=>{const mode=b.dataset.upright;if(mode==='level')current.edits.geometry.straighten=0;if(mode==='auto'){current.edits.geometry.vertical=0;current.edits.geometry.horizontal=0;current.edits.geometry.straighten=0}if(mode==='full'){current.edits.geometry.vertical=0;current.edits.geometry.horizontal=0;current.edits.geometry.aspect=0}}));
  bindCurveEvents();
}
function applyWB(mode){const vals={"As Shot":[0,0],Auto:[0,0],Daylight:[8,0],Cloudy:[15,1],Shade:[24,2],Tungsten:[-35,0],Fluorescent:[-18,12],Flash:[10,2]}[mode]||[0,0];current.edits.color.temperature=vals[0];current.edits.color.tint=vals[1]}
function resetPanel(name){const d=E.defaultEdits(),map={Profile:['profile','profileAmount','bw'],Light:['light'],'Tone Curve':['curve'],Color:['color'],'Color Mixer':['mixer','pointColor'],'Color Grading':['grading'],Effects:['effects'],Detail:['detail'],Optics:['optics'],'Crop & Geometry':['geometry']};commit(`Reset ${name}`,()=>map[name].forEach(k=>current.edits[k]=E.clone(d[k])))}
function refreshControls(){if(!current)return;$$('input[data-path]').forEach(el=>{const v=getPath(current.edits,el.dataset.path);if(v!=null){el.value=v;const out=document.querySelector(`[data-out="${el.dataset.path}"]`);if(out)out.value=fmt(v)}});$$('[data-select-path]').forEach(el=>{const v=getPath(current.edits,el.dataset.selectPath);if(v!=null)el.value=v});$$('[data-check-path]').forEach(el=>el.checked=!!getPath(current.edits,el.dataset.checkPath));if($('#pointSwatch'))$('#pointSwatch').style.background=`hsl(${current.edits.pointColor.hue} 75% 50%)`;drawCurve();updateMaskUI();updateUndoButtons()}

function drawCurve(){const c=$('#curveCanvas');if(!c||!current)return;const x=c.getContext('2d'),w=c.width,h=c.height,pts=current.edits.curve[curveChannel];x.clearRect(0,0,w,h);x.fillStyle='#111416';x.fillRect(0,0,w,h);x.strokeStyle='#2d3439';x.lineWidth=1;for(let i=1;i<4;i++){x.beginPath();x.moveTo(w*i/4,0);x.lineTo(w*i/4,h);x.stroke();x.beginPath();x.moveTo(0,h*i/4);x.lineTo(w,h*i/4);x.stroke()}x.strokeStyle='#4c555d';x.beginPath();x.moveTo(0,h);x.lineTo(w,0);x.stroke();x.strokeStyle={rgb:'#edf3f7',red:'#ff6b6b',green:'#68d486',blue:'#6da3ff'}[curveChannel];x.lineWidth=2;x.beginPath();pts.slice().sort((a,b)=>a[0]-b[0]).forEach((p,i)=>{const px=p[0]/255*w,py=h-p[1]/255*h;i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke();x.fillStyle=x.strokeStyle;pts.forEach(p=>{x.beginPath();x.arc(p[0]/255*w,h-p[1]/255*h,4,0,Math.PI*2);x.fill()});$$('[data-curve-channel]').forEach(b=>{const active=b.dataset.curveChannel===curveChannel;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))})}
function bindCurveEvents(){const c=$('#curveCanvas');let point=null,before=null;const pos=e=>{const r=c.getBoundingClientRect();return[Math.round((e.clientX-r.left)/r.width*255),Math.round(255-(e.clientY-r.top)/r.height*255)]};c.onpointerdown=e=>{if(!current)return;clearPresetTracking();before=E.clone(current.edits);const [px,py]=pos(e),pts=current.edits.curve[curveChannel];point=pts.find(p=>Math.hypot(p[0]-px,p[1]-py)<18);if(!point){point=[px,py];pts.push(point);pts.sort((a,b)=>a[0]-b[0])}c.setPointerCapture(e.pointerId);drawCurve()};c.onpointermove=e=>{if(!point)return;const[px,py]=pos(e),pts=current.edits.curve[curveChannel],isEnd=point[0]===0||point[0]===255;point[0]=isEnd?point[0]:Math.max(1,Math.min(254,px));point[1]=Math.max(0,Math.min(255,py));pts.sort((a,b)=>a[0]-b[0]);drawCurve();scheduleRender()};c.onpointerup=()=>{if(before)pushHistory(before,current.edits,'Tone curve');point=null;before=null;debounceSave()};c.ondblclick=e=>{const[px,py]=pos(e),pts=current.edits.curve[curveChannel],i=pts.findIndex(p=>p[0]!==0&&p[0]!==255&&Math.hypot(p[0]-px,p[1]-py)<22);if(i>=0)commit('Remove curve point',()=>pts.splice(i,1))}}

function buildMaskPanel(){const subject=`<div class="mask-type"><button id="subjectMaskBtn" aria-pressed="false">◎ Subject focus mask</button>${range('mask.size','Size',5,90,1)}${range('mask.feather','Feather',0,100,1)}${range('mask.subjectExposure','Subject exposure',-2,2,.01)}${range('mask.subjectClarity','Subject clarity',-100,100,1)}${range('mask.backgroundExposure','Background exposure',-2,2,.01)}${range('mask.backgroundBlur','Background blur',0,100,1)}</div>`;const sky=`<div class="mask-type"><button id="skyMaskBtn" aria-pressed="false">◒ Sky gradient mask</button>${range('mask.skyExposure','Sky exposure',-2,2,.01)}${range('mask.skyTemperature','Sky temperature',-100,100,1)}</div>`;const cleanup=`<div class="mask-type"><button id="cleanupMaskBtn" aria-pressed="false">✦ Spot cleanup</button><p class="curve-help">Click dust or a blemish; Luma samples nearby texture.</p><button id="undoSpot" class="mini-btn">Remove last spot</button></div>`;$('#maskControls').innerHTML=`<label class="check-row">Enable current mask<input type="checkbox" data-check-path="mask.enabled"></label><label class="check-row">Invert mask<input type="checkbox" data-check-path="mask.invert"></label><label class="check-row">Show overlay<input type="checkbox" data-check-path="mask.show"></label>${subject}${sky}${cleanup}`;bindRanges($('#maskControls'));$$('#maskControls [data-check-path]').forEach(el=>el.onchange=()=>commit(el.dataset.checkPath,()=>setPath(current.edits,el.dataset.checkPath,el.checked)));$('#subjectMaskBtn').onclick=()=>commit('Subject mask',()=>{current.edits.mask.enabled=true;current.edits.mask.type='subject';setTool('focus')});$('#skyMaskBtn').onclick=()=>commit('Sky mask',()=>{current.edits.mask.enabled=true;current.edits.mask.type='sky';setTool('')});$('#cleanupMaskBtn').onclick=()=>setTool('cleanup');$('#undoSpot').onclick=()=>commit('Remove spot',()=>current.edits.cleanup.pop())}
function updateMaskUI(){if(!current)return;const m=current.edits.mask;[['#subjectMaskBtn',m.enabled&&m.type==='subject'],['#skyMaskBtn',m.enabled&&m.type==='sky']].forEach(([selector,active])=>{const button=$(selector);button?.classList.toggle('active',active);button?.setAttribute('aria-pressed',String(active))});const overlay=$('#maskOverlay');overlay.classList.toggle('hidden',!m.enabled||!m.show||m.type==='sky');overlay.style.left=`${m.x*100}%`;overlay.style.top=`${m.y*100}%`;overlay.style.width=`${m.size*2}%`;overlay.style.height=`${m.size*1.44}%`}

function buildPresets(){const groups=['All',...new Set(presets.map(p=>p.group))];$('#presetGroups').innerHTML=groups.map((g,i)=>`<button class="${i?'':'active'}" data-group="${g}" aria-pressed="${!i}">${g}</button>`).join('');$$('#presetGroups button').forEach(b=>b.onclick=()=>{$$('#presetGroups button').forEach(x=>{const active=x===b;x.classList.toggle('active',active);x.setAttribute('aria-pressed',String(active))});renderPresetGrid(b.dataset.group)});renderPresetGrid('All')}
function renderPresetGrid(group='All'){const q=$('#presetSearch').value.toLowerCase();const list=presets.filter(p=>(group==='All'||p.group===group)&&p.name.toLowerCase().includes(q));$('#presetGrid').innerHTML=list.map(p=>`<button class="preset" data-name="${safeText(p.name)}" style="background:${p.style}"><b>${safeText(p.name)}</b><span>${safeText(p.group)} · ${safeText(p.source)}</span></button>`).join('');$$('.preset').forEach(b=>b.onclick=()=>applyPreset(presets.find(p=>p.name===b.dataset.name),+$('#presetAmount').value))}
function blendPreset(base,patch,t){const out=E.clone(base);function walk(dst,src,b){for(const[k,v]of Object.entries(src)){if(Array.isArray(v)){if(k==='rgb'||['red','green','blue'].includes(k))dst[k]=v.map(([px,py])=>[px,Math.max(0,Math.min(255,Math.round(px+(py-px)*t)))]);else dst[k]=E.clone(v)}else if(v&&typeof v==='object'){if(!dst[k])dst[k]={};walk(dst[k],v,b?.[k]||{})}else if(typeof v==='number'){const bv=typeof b?.[k]==='number'?b[k]:0;dst[k]=bv+(v-bv)*t}else if(typeof v==='boolean')dst[k]=t>0?v:b?.[k]||false;else dst[k]=t>0?v:b?.[k]}}walk(out,patch,base);return out}
function applyPreset(p,amount=100){
  if(!current)return;
  if(batchPresetMode){const targets=photos.filter(photo=>photo.selected),changes=targets.map(photo=>({id:photo.id,before:E.clone(photo.edits),after:blendPreset(photo.edits,p.patch,amount/100)}));batchPresetMode=false;if(!changes.length)return toast('Select photographs before applying a batch preset');if(!pushBulkHistory(changes,`Preset ${p.name} · ${targets.length} photos`))return;for(const change of changes){const photo=photos.find(candidate=>candidate.id===change.id);if(photo)photo.edits=E.clone(change.after)}clearPresetTracking();refreshControls();scheduleRender();debounceSave();if(view==='library')updateLibrary();toast(`${p.name} applied to ${targets.length} selected photos · Undo reverses the batch`);return}
  if(activePreset!==p){activePreset=p;presetBase=E.clone(current.edits)}const before=E.clone(current.edits),next=blendPreset(presetBase,p.patch,amount/100);current.edits=next;pushHistory(before,next,`Preset: ${p.name}`);refreshControls();scheduleRender();debounceSave();toast(`${p.name} · ${amount}%`)
}

async function importPhotos(items){
  try{if(!items)items=await window.desktop.pickImages()}catch(error){reportFailure('Choose photos',error,'The photo picker could not be opened.');return}
  if(!items?.length)return;let firstNew=null,added=0,limited=0;const knownPaths=new Set(photos.map(photo=>photo.filePath.toLowerCase()));
  for(const f of items){if(photos.length>=MAX_CATALOG_PHOTOS){limited++;continue}const filePath=typeof f?.filePath==='string'?f.filePath:'';if(!filePath)continue;const pathKey=filePath.toLowerCase();if(knownPaths.has(pathKey))continue;knownPaths.add(pathKey);const p=E.migratePhoto({...f,filePath,id:uid(),importedAt:Date.now()+added});photos.push(p);firstNew??=p;added++}
  if(!added)return toast(limited?'The catalog photo limit has been reached':'Those photos are already in the catalog');catalogDirty=true;const saved=saveCatalog();updateLibrary();selectPhoto(firstNew);toast(saved?`${added} photo${added===1?'':'s'} imported${limited?` · ${limited} skipped at the catalog limit`:''}`:`${added} photo${added===1?'':'s'} available for this session, but the catalog is not saved · back up before closing`)
}
function clearPreview(){const c=$('#canvas');if(c){c.width=1;c.height=1;c.getContext('2d')?.clearRect(0,0,1,1)}const h=$('#hist');h?.getContext('2d')?.clearRect(0,0,h.width,h.height)}
function clearPrefetch(){for(const im of prefetchCache.values()){im.onload=im.onerror=null;try{im.src=''}catch{}}prefetchCache.clear()}
function prefetchAround(p){
  const index=photos.indexOf(p);if(index<0)return;const wanted=[];for(let distance=1;distance<=PREFETCH_RADIUS;distance++){if(photos[index+distance])wanted.push(photos[index+distance]);if(photos[index-distance])wanted.push(photos[index-distance])}const wantedIds=new Set(wanted.slice(0,MAX_PREFETCH_IMAGES).map(x=>x.id));
  for(const[id,im]of prefetchCache)if(!wantedIds.has(id)){im.onload=im.onerror=null;try{im.src=''}catch{}prefetchCache.delete(id)}
  for(const photo of wanted.slice(0,MAX_PREFETCH_IMAGES)){if(prefetchCache.has(photo.id))continue;const im=new Image();im.crossOrigin='anonymous';im.decoding='async';im._lumaUrl=photo.url||`local-image://load?path=${encodeURIComponent(photo.filePath)}`;im.onerror=()=>{if(prefetchCache.get(photo.id)===im)prefetchCache.delete(photo.id)};prefetchCache.set(photo.id,im);im.src=im._lumaUrl}
}
function selectPhoto(p,{openEditor=true}={}){
  if(!p)return;current=p;activePreset=null;presetBase=null;const token=++imageLoadToken;renderGeneration++;renderQueued=false;clearPreview();syncCurrentIndicators();
  const cached=prefetchCache.get(p.id),nextImage=cached||new Image();prefetchCache.delete(p.id);sourceImage=nextImage;nextImage.crossOrigin='anonymous';nextImage.decoding='async';let settled=false;
  const finishFailure=error=>{if(settled||token!==imageLoadToken||current!==p)return;settled=true;clearTimeout(timer);nextImage.onload=nextImage.onerror=null;try{nextImage.src=''}catch{}p._loadError=true;clearPreview();setView('library');updateLibrary();console.error('[Luma] Load photo',error);toast(`Could not open ${p.name}. The file may be missing or unsupported; choose another photo.`)};
  const timer=setTimeout(()=>finishFailure(new Error('Image load timed out')),IMAGE_LOAD_TIMEOUT);
  nextImage.onload=()=>{if(settled||token!==imageLoadToken||current!==p)return;if(!nextImage.naturalWidth||!nextImage.naturalHeight)return finishFailure(new Error('Decoded image has no pixels'));settled=true;clearTimeout(timer);delete p._loadError;prefetchAround(p);if(openEditor||view==='edit'){scheduleRender();showEditor()}else syncCurrentIndicators()};
  nextImage.onerror=()=>finishFailure(new Error('Image decode failed'));
  const url=p.url=`local-image://load?path=${encodeURIComponent(p.filePath)}`;nextImage._lumaUrl=url;if(!cached)nextImage.src=url;else if(nextImage.complete)queueMicrotask(()=>nextImage.naturalWidth?nextImage.onload?.():nextImage.onerror?.());refreshControls();renderFilmstrip();updateUndoButtons()
}
function updateViewTabs(){ $$('.tab').forEach(x=>{const active=x.dataset.view===view;x.classList.toggle('active',active);if(active)x.setAttribute('aria-current','page');else x.removeAttribute('aria-current')}) }
function showEditor(){view='edit';document.body.classList.remove('library-mode');$('#empty').classList.add('hidden');$('#library').classList.add('hidden');$('#editor').classList.remove('hidden');$('#filmstrip').classList.remove('hidden');$('#adjustPanel').classList.remove('hidden');updateViewTabs();updateActionState()}
function setView(v){view=v;document.body.classList.toggle('library-mode',v==='library');if(v==='library'){if(toolMode)setTool('');dismissToast();$('#empty').classList.add('hidden');$('#editor').classList.add('hidden');$('#filmstrip').classList.add('hidden');$('#adjustPanel').classList.add('hidden');$('#library').classList.remove('hidden');updateLibrary()}else if(current?._loadError)selectPhoto(current);else if(current){showEditor();scheduleRender()}else{$('#library').classList.add('hidden');$('#empty').classList.remove('hidden')}updateViewTabs();updateActionState()}
function scheduleRender(){
  if(renderQueued||!current||!sourceImage.complete||!sourceImage.naturalWidth||!sourceImage.naturalHeight)return;
  const photo=current,image=sourceImage,generation=renderGeneration;renderQueued=true;
  requestAnimationFrame(()=>{renderQueued=false;if(photo!==current||image!==sourceImage||generation!==renderGeneration){scheduleRender();return}
    try{
      const edits=compare?E.defaultEdits():photo.edits,c=$('#canvas'),ctx=c?.getContext('2d',{willReadFrequently:true});if(!c||!ctx)throw new Error('Preview canvas is unavailable');
      let out;try{out=E.render(image,edits,{maxEdge:1050})}catch(firstError){if(firstError instanceof RangeError||/memory|canvas|large|allocation/i.test(String(firstError?.message)))out=E.render(image,edits,{maxEdge:640});else throw firstError}
      if(photo!==current||image!==sourceImage||generation!==renderGeneration)return;c.width=out.width;c.height=out.height;ctx.drawImage(out,0,0);
      if(clipping){const im=ctx.getImageData(0,0,c.width,c.height),d=im.data;for(let i=0;i<d.length;i+=4){const lo=Math.max(d[i],d[i+1],d[i+2])<4,hi=Math.min(d[i],d[i+1],d[i+2])>251;if(lo){d[i]=35;d[i+1]=95;d[i+2]=255}else if(hi){d[i]=255;d[i+1]=45;d[i+2]=38}}ctx.putImageData(im,0,0)}
      drawHistogram();updateMaskUI()
    }catch(error){clearPreview();reportFailure('Render preview',error,'Preview rendering failed. Try resetting the current panel or choosing another photo.')}
  })
}
function drawHistogram(){try{const src=$('#canvas'),h=$('#hist');if(!src?.width||!h)return;const t=document.createElement('canvas');t.width=96;t.height=55;const tx=t.getContext('2d',{willReadFrequently:true});if(!tx)return;tx.drawImage(src,0,0,t.width,t.height);const d=tx.getImageData(0,0,t.width,t.height).data,bins=[Array(64).fill(0),Array(64).fill(0),Array(64).fill(0)];for(let i=0;i<d.length;i+=4)for(let c=0;c<3;c++)bins[c][Math.min(63,d[i+c]>>2)]++;const x=h.getContext('2d'),max=Math.max(1,...bins.flat());if(!x)return;x.clearRect(0,0,h.width,h.height);[['#ff6b6b88',0],['#6cd98a88',1],['#6da2ff99',2]].forEach(([color,c])=>{x.beginPath();x.moveTo(0,h.height);bins[c].forEach((v,i)=>x.lineTo(i/63*h.width,h.height-v/max*(h.height-5)));x.lineTo(h.width,h.height);x.fillStyle=color;x.fill()})}catch(error){console.warn('[Luma] Histogram unavailable',error)}}
function renderFilmstrip(){const currentIndex=Math.max(0,photos.indexOf(current)),half=Math.floor(MAX_FILMSTRIP_THUMBS/2),start=Math.max(0,Math.min(currentIndex-half,Math.max(0,photos.length-MAX_FILMSTRIP_THUMBS))),visible=photos.slice(start,start+MAX_FILMSTRIP_THUMBS);$('#filmstrip').innerHTML=visible.map((p,i)=>`<button class="thumb-wrap filmstrip-item" data-i="${start+i}" aria-label="Open ${safeAttr(p.name)}" ${p===current?'aria-current="true"':''}><img class="thumb ${p===current?'active':''}" src="${p.url}" alt=""><span class="thumb-rating" aria-hidden="true">${'★'.repeat(p.rating)}</span></button>`).join('');$$('.filmstrip-item').forEach(t=>t.onclick=()=>selectPhoto(photos[+t.dataset.i]))}

function filteredPhotos(){const q=$('#search')?.value.toLowerCase()||'',min=+($('#filterRating')?.value||0),sort=$('#sort')?.value||'newest';let list=photos.filter(p=>{if(activeFilter==='picks'&&p.flag!=='pick')return false;if(activeFilter==='unrated'&&p.rating)return false;if(activeFilter==='issues'&&!p.quality?.issue)return false;if(p.rating<min)return false;return !q||p.name.toLowerCase().includes(q)||p.tags.join(' ').toLowerCase().includes(q)||p.caption.toLowerCase().includes(q)});return list.sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):sort==='rating'?b.rating-a.rating:sort==='quality'?(b.quality?.score||0)-(a.quality?.score||0):b.importedAt-a.importedAt)}
function updateActionState(){const selected=photos.filter(p=>p.selected),targets=selected.filter(p=>p!==current),hasCurrent=!!current,hasPhotos=photos.length>0;$('#exportBtn').disabled=!hasCurrent;$('#exportBtn').title=hasCurrent?`Export active photograph: ${current.name}`:'Import a photograph to export';$('#exportBtn').setAttribute('aria-label',$('#exportBtn').title);$('#cullBtn').disabled=!hasPhotos;$('#batchBtn').disabled=!hasCurrent||!targets.length;$('#batchBtn').title=hasCurrent?`Copy edits from ${current.name} to ${targets.length} selected target${targets.length===1?'':'s'}`:'Choose an active source photograph';$('#mergeBtn').disabled=selected.length<2;$('#compareSelectedBtn').disabled=selected.length!==2;$('#batchPresetBtn').disabled=!selected.length;$('#selectAllBtn').disabled=!filteredPhotos().length;$('#deselectBtn').disabled=!selected.length;$('#doExport').disabled=!hasCurrent;if($('#exportTarget'))$('#exportTarget').textContent=hasCurrent?`Active photograph: ${current.name}`:'No active photograph'}
function syncCurrentIndicators(){if($('#libraryTarget'))$('#libraryTarget').textContent=current?`Active: ${current.name} · Export, rating and flag shortcuts target this photograph`:'No active photograph';$$('.card').forEach(card=>{const active=card._photo===current;card.classList.toggle('current',active);if(active)card.setAttribute('aria-current','true');else card.removeAttribute('aria-current');card.querySelector('.current-badge')?.classList.toggle('hidden',!active)});updateActionState()}
function updateLibrary(){const list=filteredPhotos(),visible=list.slice(0,libraryRenderLimit),selected=photos.filter(p=>p.selected),hasPhotos=photos.length>0;$('#photoCount').textContent=photos.length;$('#issueCount').textContent=photos.filter(p=>p.quality?.issue).length;$('#librarySubtitle').textContent=`${list.length} photograph${list.length===1?'':'s'} · ${photos.filter(p=>p.flag==='pick').length} picks`;$('#selectionBar').classList.toggle('hidden',!selected.length);$('#selectedCount').textContent=`${selected.length} selected`;$('#grid').innerHTML=visible.map(p=>`<article class="card ${p.selected?'selected':''}" role="button" tabindex="0" aria-label="Activate ${safeAttr(p.name)}${p.selected?', selected':''}"><img src="${p.url}" alt="Thumbnail of ${safeAttr(p.name)}"><span class="current-badge hidden">Active</span><div class="card-top"><button class="select-box" aria-label="${p.selected?'Deselect':'Select'} ${safeAttr(p.name)}" aria-pressed="${p.selected}">${p.selected?'✓':''}</button><button class="info-btn" aria-label="Photo info for ${safeAttr(p.name)}">ⓘ</button></div><div class="card-meta"><span class="stars" aria-label="${p.rating} stars">${'★'.repeat(p.rating)}</span>${p.quality?.issue?` <span class="issue">${safeText(p.quality.issue)}</span>`:''}</div><div class="caption">${p.flag==='pick'?'⚑ ':p.flag==='reject'?'× ':''}${safeText(p.name)}${p.quality?` · ${p.quality.score}`:''}</div>${p.label?`<i class="color-label ${p.label}" aria-label="${p.label} color label"></i>`:''}</article>`).join('');$$('.card').forEach((card,index)=>{const p=visible[index];card._photo=p;card.onclick=e=>{if(e.target.closest('button'))return;selectPhoto(p,{openEditor:false})};card.ondblclick=e=>{if(e.target.closest('button'))return;selectPhoto(p)};card.onkeydown=e=>{if(e.target!==card)return;if(e.key==='Enter'){e.preventDefault();selectPhoto(p)}else if(e.key===' '){e.preventDefault();selectPhoto(p,{openEditor:false})}};card.querySelector('.select-box').onclick=e=>{e.stopPropagation();p.selected=!p.selected;updateLibrary()};card.querySelector('.info-btn').onclick=e=>{e.stopPropagation();if(current!==p)selectPhoto(p,{openEditor:false});openMetadata(p)}});syncCurrentIndicators();const more=$('#libraryMore'),remaining=Math.max(0,list.length-visible.length);more?.classList.toggle('hidden',!remaining);if(remaining)$('#libraryMoreText').textContent=`Showing ${visible.length} of ${list.length} photographs`;$('#empty').classList.toggle('hidden',hasPhotos);if(view==='library')$('#library').classList.toggle('hidden',!hasPhotos);if(!hasPhotos)$('#adjustPanel').classList.add('hidden');updateActionState()}
function openMetadata(p){metadataPhoto=p;metadataRating=p.rating;$('#flagEditor').value=p.flag;$('#labelEditor').value=p.label;$('#tagsEditor').value=p.tags.join(', ');$('#captionEditor').value=p.caption;renderRating(metadataRating);$('#metadataDialog').showModal()}
function renderRating(r,focusRating=0){$('#ratingEditor').innerHTML=[1,2,3,4,5].map(n=>`<button type="button" class="${n<=r?'on':''}" data-rating="${n}" aria-label="${n} star${n===1?'':'s'}" aria-pressed="${n<=r}">★</button>`).join('');$$('#ratingEditor button').forEach(b=>b.onclick=()=>{const rating=+b.dataset.rating;metadataRating=metadataRating===rating?0:rating;renderRating(metadataRating,rating)});if(focusRating)requestAnimationFrame(()=>$('#ratingEditor [data-rating="'+focusRating+'"]')?.focus())}
async function analyzeCatalog(){if(!photos.length)return toast('Import photos first');toast('Analyzing sharpness and exposure…');let failed=0;const snapshot=photos.slice();for(let i=0;i<snapshot.length;i++){const p=snapshot[i];try{const im=await loadImage(p.url);p.quality=await E.analyze(im)}catch(error){failed++;console.warn(`[Luma] Analysis skipped ${p.name}`,error)}if(i%5===0){toast(`Analyzing ${i+1} of ${snapshot.length}…`);await new Promise(r=>setTimeout(r,0))}}catalogDirty=true;saveCatalog();updateLibrary();toast(`Analysis complete · ${photos.filter(p=>p.quality?.issue).length} need review${failed?` · ${failed} skipped`:''}`)}
function autoTone(){if(!sourceImage.complete||!sourceImage.naturalWidth||!current)return;const photo=current,image=sourceImage;runAsync('Auto tone',async()=>{const q=await E.analyze(image);if(current!==photo||sourceImage!==image)return;commit('Auto tone',()=>{const a=photo.edits.light;a.exposure=Math.max(-2,Math.min(2,Math.log2(.5/Math.max(.05,q.exposure))));a.highlights=-35;a.shadows=35;a.whites=10;a.blacks=-10;a.contrast=8;photo.edits.color.vibrance=10})},'Auto tone could not analyze this photo.')}
const loadImage=(url,timeout=IMAGE_LOAD_TIMEOUT)=>new Promise((resolve,reject)=>{const im=new Image();let settled=false,timer;const done=(error,value)=>{if(settled)return;settled=true;clearTimeout(timer);im.onload=im.onerror=null;error?reject(error):resolve(value)};im.crossOrigin='anonymous';im.decoding='async';im.onload=()=>im.naturalWidth&&im.naturalHeight?done(null,im):done(new Error('Decoded image has no pixels'));im.onerror=()=>done(new Error('Image decode failed'));timer=setTimeout(()=>{im.src='';done(new Error('Image load timed out'))},timeout);im.src=url});

async function compareSelected(){
  const selected=photos.filter(p=>p.selected);if(selected.length!==2)return toast('Select exactly two photos to compare');
  const dialog=$('#compareDialog'),canvases=[$('#compareCanvasA'),$('#compareCanvasB')],labels=[$('#compareNameA'),$('#compareNameB')];
  canvases.forEach(c=>{c.width=c.height=1});labels.forEach((label,i)=>label.textContent=`Loading ${selected[i].name}…`);dialog.showModal();
  const images=await Promise.all(selected.map(p=>loadImage(p.url)));
  if(!dialog.open)return;
  for(let i=0;i<2;i++){
    const rendered=E.render(images[i],selected[i].edits,{maxEdge:900}),canvas=canvases[i],ctx=canvas.getContext('2d');if(!ctx)throw new Error('Compare canvas is unavailable');
    canvas.width=rendered.width;canvas.height=rendered.height;ctx.drawImage(rendered,0,0);labels[i].textContent=`${selected[i].name} · ${'★'.repeat(selected[i].rating)||'Unrated'}${selected[i].flag==='pick'?' · Pick':selected[i].flag==='reject'?' · Rejected':''}`;rendered.width=rendered.height=1;
  }
}

async function mergeSelected(kind){const selected=photos.filter(p=>p.selected);if(selected.length<2)return toast('Select at least two photos');if(selected.length>12)return toast('Merge up to 12 photos at a time to avoid running out of memory');toast(kind==='hdr'?'Blending exposures…':'Building panorama…');const ims=await Promise.all(selected.map(p=>loadImage(p.url)));let out=document.createElement('canvas'),x=out.getContext('2d');if(!x)throw new Error('Merge canvas is unavailable');if(kind==='hdr'){const w=Math.min(...ims.map(i=>i.naturalWidth),3000),h=Math.round(w*ims[0].naturalHeight/ims[0].naturalWidth);out.width=w;out.height=h;x.globalAlpha=1/ims.length;ims.forEach(im=>x.drawImage(im,0,0,w,h));x.globalAlpha=1}else{const h=Math.min(1400,...ims.map(i=>i.naturalHeight)),widths=ims.map(i=>Math.round(i.naturalWidth*h/i.naturalHeight)),overlap=Math.round(h*.08),totalWidth=widths.reduce((a,b)=>a+b,0)-overlap*(ims.length-1);if(totalWidth>16384||totalWidth*h>50_000_000)throw new RangeError('The panorama would be too large. Merge fewer photos.');out.width=totalWidth;out.height=h;let xx=0;ims.forEach((im,i)=>{x.globalAlpha=i?0.9:1;x.drawImage(im,xx,0,widths[i],h);xx+=widths[i]-overlap});x.globalAlpha=1}const blob=await new Promise((resolve,reject)=>out.toBlob(value=>value?resolve(value):reject(new Error('Merge encoding failed')),'image/jpeg',.94)),bytes=await blob.arrayBuffer(),result=await window.desktop.exportImage({bytes,mime:'image/jpeg',suggestedName:kind==='hdr'?'Luma-HDR-Merge':'Luma-Panorama',format:'jpg'});out.width=out.height=1;if(result){await importPhotos([{filePath:result,name:result.split(/[\\/]/).pop(),url:`local-image://load?path=${encodeURIComponent(result)}`}]);toast('Merged photograph added to catalog')}}
function syncSelected(){const targets=photos.filter(photo=>photo.selected&&photo!==current);if(!current||!targets.length)return toast('Choose an active source and select at least one different target');const changes=targets.map(photo=>({id:photo.id,before:E.clone(photo.edits),after:E.clone(current.edits)}));if(!pushBulkHistory(changes,`Sync from ${current.name} · ${targets.length} targets`))return;for(const change of changes){const photo=photos.find(candidate=>candidate.id===change.id);if(photo)photo.edits=E.clone(change.after)}debounceSave();if(view==='library')updateLibrary();toast(`Synced edits from ${current.name} to ${targets.length} photograph${targets.length===1?'':'s'} · Undo reverses the batch`)}

function setTool(mode){toolMode=toolMode===mode?'':mode;[['#pickColorBtn','color'],['#focusModeBtn','focus'],['#cleanupModeBtn','cleanup'],['#cleanupMaskBtn','cleanup']].forEach(([s,m])=>{const button=$(s),active=toolMode===m;button?.classList.toggle('active',active);button?.setAttribute('aria-pressed',String(active))});if(toolMode)toast({color:'Click a color in the photograph',point:'Click the exact color to refine',focus:'Click the subject to position focus',cleanup:'Click a spot to clean it'}[toolMode])}
function canvasClick(e){if(!current||!toolMode)return;const c=$('#canvas'),r=c.getBoundingClientRect();if(!r.width||!r.height)return;const x=Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y=Math.max(0,Math.min(1,(e.clientY-r.top)/r.height));if(toolMode==='focus')commit('Position focus',()=>{current.edits.mask.enabled=true;current.edits.mask.type='subject';current.edits.mask.x=x;current.edits.mask.y=y});else if(toolMode==='cleanup'){if(current.edits.cleanup.length>=MAX_CLEANUP_SPOTS)return toast(`Cleanup is limited to ${MAX_CLEANUP_SPOTS} spots per photo`);commit('Cleanup spot',()=>current.edits.cleanup.push({x,y,size:1.8}))}else if(toolMode==='color'||toolMode==='point'){try{const px=Math.min(c.width-1,Math.floor(x*c.width)),py=Math.min(c.height-1,Math.floor(y*c.height)),ctx=c.getContext('2d');if(!ctx)throw new Error('Preview canvas is unavailable');const d=ctx.getImageData(px,py,1,1).data,[h]=E.rgbToHsl(d[0]/255,d[1]/255,d[2]/255);if(toolMode==='point')commit('Point color sample',()=>{current.edits.pointColor.enabled=true;current.edits.pointColor.hue=Math.round(h)});else{mixerColor=E.COLORS.reduce((best,name)=>{const dist=Math.abs((((h-E.HUE_CENTERS[name])+540)%360)-180);return dist<best[1]?[name,dist]:best},['red',999])[0];buildMixerSliders();toast(`${mixerColor} color range selected`)}switchRightPanel('edit');const colorPanel=$('[data-panel-name="Color Mixer"]');colorPanel.classList.remove('collapsed');colorPanel.scrollIntoView({behavior:'smooth'})}catch(error){reportFailure('Sample preview color',error,'That color could not be sampled from the preview.')}}setTool('')}

function switchRightPanel(name){$$('.panel-tabs button').forEach(b=>{const active=b.dataset.panel===name;b.classList.toggle('active',active);b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1});$('#editPanel').classList.toggle('hidden',name!=='edit');$('#presets').classList.toggle('hidden',name!=='presets');$('#maskPanel').classList.toggle('hidden',name!=='mask')}
function updateExportOptions(){const format=$('#exportFormat').value,original=format==='original',lossless=format==='png'||format==='tiff';$('#exportQuality').disabled=original||lossless;$('#exportSize').disabled=original;$('#exportWatermark').disabled=original;$('#exportQualityField').classList.toggle('disabled-field',original||lossless);$('#exportSizeField').classList.toggle('disabled-field',original);$('#exportWatermarkField').classList.toggle('disabled-field',original);const note=$('#exportFormatNote');if(original){note.textContent='Original file copies the source unchanged; resize, quality, watermark, and current edits do not apply.';note.classList.remove('hidden')}else if(lossless){note.textContent='This format is lossless, so the Quality setting does not apply.';note.classList.remove('hidden')}else note.classList.add('hidden');updateActionState()}
let activeExportWorker=null,activeExportCancel=null,exportJob=0;
function exportAbortError(){return new DOMException('Export canceled','AbortError')}
function cancelExportRender(){exportJob++;const cancel=activeExportCancel;activeExportCancel=null;if(cancel){cancel();return}if(activeExportWorker){activeExportWorker.terminate();activeExportWorker=null}}
async function renderExportInWorker(image,edits,options){
  if(typeof Worker!=='function'||typeof createImageBitmap!=='function')throw new Error('Background export is unavailable on this system.');
  cancelExportRender();const job=++exportJob;let bitmap;try{bitmap=await createImageBitmap(image)}catch(error){if(job!==exportJob)throw exportAbortError();throw error}if(job!==exportJob){bitmap.close();throw exportAbortError()}
  let worker;try{worker=new Worker('render-worker.js')}catch(error){bitmap.close();throw error}const id=`export-${Date.now()}-${job}`;activeExportWorker=worker;
  return new Promise((resolve,reject)=>{let settled=false,timeout;const finish=(error,value)=>{if(settled)return;settled=true;clearTimeout(timeout);if(activeExportWorker===worker)activeExportWorker=null;if(activeExportCancel===cancel)activeExportCancel=null;worker.onmessage=worker.onerror=worker.onmessageerror=null;worker.terminate();error?reject(error):resolve(value)},cancel=()=>finish(exportAbortError());activeExportCancel=cancel;timeout=setTimeout(()=>finish(new Error('Export rendering timed out. Try a smaller output size.')),180000);worker.onerror=event=>{event.preventDefault?.();finish(new Error(event.message||'The background export worker failed.'))};worker.onmessageerror=()=>finish(new Error('The background export worker returned an unreadable response.'));worker.onmessage=event=>{const message=event.data||{};if(message.id!==id)return;if(message.progress){toast(message.progress==='encoding'?'Encoding export…':'Rendering export in the background…');return}if(message.error){finish(new Error(message.error));return}if(message.bytes)finish(null,message)};try{worker.postMessage({id,bitmap,edits,maxEdge:options.maxEdge,watermark:options.watermark,mime:options.mime,quality:options.quality},[bitmap])}catch(error){bitmap.close();finish(error)}})
}
async function doExport(){
  if(!current)return;const photo=current,image=sourceImage,dialog=$('#exportDialog'),exportButton=$('#doExport');let completed=false;exportButton.disabled=true;dialog.setAttribute('aria-busy','true');
  try{
    const format=$('#exportFormat').value;if(format==='original'){const result=await window.desktop.copyOriginal({filePath:photo.filePath,suggestedName:photo.name});if(result){completed=true;toast('Original copied');await window.desktop.revealFile(result)}return}
    if(!image.complete||!image.naturalWidth||image!==sourceImage)throw new Error('The selected photo has not finished loading.');
    toast('Preparing background export…');await new Promise(r=>setTimeout(r,30));
    const size=Math.max(0,Math.round(num($('#exportSize').value,0))),quality=Math.max(.1,Math.min(1,num($('#exportQuality').value,92)/100)),watermark=$('#exportWatermark').value.trim().slice(0,80),exportEdits=E.clone(photo.edits);exportEdits.pointColor.visualize=false;
    const mime={jpg:'image/jpeg',png:'image/png',webp:'image/webp',tiff:'image/png'}[format]||'image/jpeg',rendered=await renderExportInWorker(image,exportEdits,{maxEdge:size||null,watermark,mime,quality});
    const result=await window.desktop.exportImage({bytes:rendered.bytes,mime:rendered.mime,suggestedName:photo.name.replace(/\.[^.]+$/,'')+'-luma',format,quality:Math.round(quality*100)});if(result){completed=true;rememberWatermark(watermark);toast('Export complete');await window.desktop.revealFile(result)}
  }catch(error){if(error?.name==='AbortError')toast('Export canceled');else reportFailure('Export photo',error,error instanceof RangeError?error.message:'Export failed. Try a smaller output size or another format.')}
  finally{dialog.removeAttribute('aria-busy');if(completed&&dialog?.open)dialog.close();else updateActionState()}
}

function updateCullState(message){if(view==='library')updateLibrary();else renderFilmstrip();debounceSave();toast(message)}
function rateCurrent(rating){if(!current)return;current.rating=Math.max(0,Math.min(5,rating));updateCullState(current.rating?`${current.rating} star${current.rating===1?'':'s'} · ${current.name}`:`Rating cleared · ${current.name}`)}
function flagCurrent(flag){if(!current)return;current.flag=flag;updateCullState(`${flag==='pick'?'Picked':flag==='reject'?'Rejected':'Flag cleared'} · ${current.name}`)}
function navigateCurrent(delta){const filtered=filteredPhotos(),list=filtered.length?filtered:photos;if(!list.length)return;let index=list.indexOf(current);if(index<0)index=delta>0?-1:list.length;const next=list[Math.max(0,Math.min(list.length-1,index+delta))];if(next&&next!==current)selectPhoto(next,{openEditor:view!=='library'})}
function shortcutContextBlocked(e){const target=e.target;return!!document.querySelector('dialog[open]')||!!target?.closest?.('textarea, select, [contenteditable="true"], input:not([type="range"])')}
function handleShortcut(e){
  const key=String(e.key||''),lower=key.toLowerCase(),modified=e.ctrlKey||e.metaKey;if(shortcutContextBlocked(e)||e.target?.matches?.('input[type="range"]')&&!modified&&key!=='F1')return;if(key==='F1'){e.preventDefault();openHelpCenter();return}
  if(modified){if(lower==='z'){e.preventDefault();e.shiftKey?$('#redoBtn').click():$('#undoBtn').click()}else if(lower==='e'){e.preventDefault();$('#exportBtn').click()}return}
  if(e.altKey)return;
  if(e.code==='Backslash'||key==='\\'){e.preventDefault();if(!compare)setCompare(true);return}
  if(key==='ArrowLeft'||key==='ArrowRight'){e.preventDefault();navigateCurrent(key==='ArrowLeft'?-1:1);return}
  if(/^[0-5]$/.test(key)){e.preventDefault();rateCurrent(+key);return}
  if(lower==='p'){e.preventDefault();flagCurrent('pick');return}if(lower==='x'){e.preventDefault();flagCurrent('reject');return}if(lower==='u'){e.preventDefault();flagCurrent('none');return}
  if(lower==='g'){e.preventDefault();setView('library');return}if(lower==='d'){e.preventDefault();setView('edit');return}if(key==='Escape')setTool('')
}
function setCompare(value){compare=!!value;$('#compareBtn')?.setAttribute('aria-pressed',String(compare));scheduleRender()}
function releaseOriginalShortcut(e){if((e.code==='Backslash'||e.key==='\\')&&compare)setCompare(false)}

function confirmCatalogRestore(restored){const dialog=$('#restoreConfirmDialog');$('#restoreConfirmSummary').textContent=`Incoming catalog: ${restored.photos.length} photograph${restored.photos.length===1?'':'s'}${restored.skipped?` (${restored.skipped} invalid entr${restored.skipped===1?'y':'ies'} skipped)`:''}. Current catalog: ${photos.length} photograph${photos.length===1?'':'s'}.`;dialog.returnValue='';dialog.showModal();return new Promise(resolve=>dialog.addEventListener('close',()=>resolve(dialog.returnValue==='restore'),{once:true}))}

function bindGlobal(){
  $('#importBtn').onclick=$('#emptyImport').onclick=()=>runAsync('Import photos',()=>importPhotos(),'Photos could not be imported.');$$('.tab').forEach(t=>t.onclick=()=>setView(t.dataset.view));$('#exportBtn').onclick=()=>{if(!current)return toast('Import a photo first');$('#exportTarget').textContent=`Active photograph: ${current.name}`;updateExportOptions();$('#exportDialog').showModal()};$('#exportFormat').onchange=updateExportOptions;$('#doExport').onclick=e=>{e.preventDefault();if(e.currentTarget.form.reportValidity())doExport()};$('#exportDialog').addEventListener('close',cancelExportRender);
  $('#helpBtn').onclick=openHelpCenter;$('#openGuideBtn').onclick=()=>runAsync('Open help guide',openHelpGuide,'The guide could not be opened.');$('#startTutorialBtn').onclick=()=>{helpReturnFocus=null;$('#helpDialog').close();requestAnimationFrame(startTutorial)};$('#tutorialBack').onclick=()=>{if(tutorialStep>0){tutorialStep--;renderTutorialStep()}};$('#tutorialNext').onclick=()=>{if(tutorialStep>=tutorialSteps.length-1)finishTutorial('complete');else{tutorialStep++;renderTutorialStep()}};$('#tutorialSkip').onclick=$('#tutorialClose').onclick=()=>finishTutorial('skipped');$('#tutorialDialog').addEventListener('cancel',event=>{event.preventDefault();finishTutorial('skipped')});$('#tutorialDialog').addEventListener('close',()=>{clearTutorialTarget();document.body.classList.remove('tutorial-active')});$('#helpDialog').addEventListener('close',()=>{const returnTo=helpReturnFocus;helpReturnFocus=null;requestAnimationFrame(()=>{if(returnTo?.isConnected&&!returnTo.closest('dialog:not([open])'))returnTo.focus()})});window.addEventListener('resize',()=>{if($('#tutorialDialog').open)placeTutorial()});
  $('#compareBtn').onpointerdown=()=>setCompare(true);['pointerup','pointerleave','pointercancel'].forEach(n=>$('#compareBtn').addEventListener(n,()=>setCompare(false)));$('#compareBtn').onkeydown=e=>{if((e.key===' '||e.key==='Enter')&&!e.repeat){e.preventDefault();setCompare(true)}};$('#compareBtn').onkeyup=e=>{if(e.key===' '||e.key==='Enter'){e.preventDefault();setCompare(false)}};$('#compareBtn').onblur=()=>setCompare(false);
  $('#rotateLeft').onclick=()=>commit('Rotate left',()=>current.edits.geometry.rotation90-=90);$('#rotateRight').onclick=()=>commit('Rotate right',()=>current.edits.geometry.rotation90+=90);$('#flipBtn').onclick=()=>commit('Flip',()=>current.edits.geometry.flipX=!current.edits.geometry.flipX);$('#resetBtn').onclick=()=>commit('Reset all',()=>current.edits=E.defaultEdits());
  $$('.panel-tabs button').forEach((b,index,buttons)=>{b.onclick=()=>switchRightPanel(b.dataset.panel);b.onkeydown=e=>{if(e.key!=='ArrowLeft'&&e.key!=='ArrowRight')return;e.preventDefault();const next=buttons[(index+(e.key==='ArrowRight'?1:-1)+buttons.length)%buttons.length];switchRightPanel(next.dataset.panel);next.focus()}});$('#presetSearch').oninput=()=>renderPresetGrid($('#presetGroups .active')?.dataset.group||'All');$('#presetAmount').oninput=e=>{$('#presetAmountOut').value=e.target.value;if(activePreset&&current){const before=current.edits;current.edits=blendPreset(presetBase,activePreset.patch,+e.target.value/100);refreshControls();scheduleRender();debounceSave()}};
  $('#pickColorBtn').onclick=()=>setTool('color');$('#focusModeBtn').onclick=()=>{if(!current)return;if(!current.edits.mask.enabled||current.edits.mask.type!=='subject')commit('Subject mask',()=>{current.edits.mask.enabled=true;current.edits.mask.type='subject'});setTool('focus');switchRightPanel('mask');refreshControls()};$('#cleanupModeBtn').onclick=()=>{setTool('cleanup');switchRightPanel('mask')};$('#canvas').onclick=canvasClick;
  $('#fitBtn').onclick=()=>{$('#zoomRange').value=100;$('#canvas').style.transform='';$('#canvasWrap').classList.remove('zoomed');$('#zoomLabel').value='Fit'};$('#zoomRange').oninput=e=>{const z=e.target.value/100;$('#canvas').style.transform=`scale(${z})`;$('#canvasWrap').classList.toggle('zoomed',z>1);$('#zoomLabel').value=e.target.value+'%'};
  $('#undoBtn').onclick=()=>{const[u,r]=historyStacks(),item=u.pop();if(!item)return;clearPresetTracking();r.push(item);applyHistoryItem(item,'before');refreshControls();scheduleRender();if(view==='library')updateLibrary();debounceSave();updateUndoButtons()};$('#redoBtn').onclick=()=>{const[u,r]=historyStacks(),item=r.pop();if(!item)return;clearPresetTracking();u.push(item);applyHistoryItem(item,'after');refreshControls();scheduleRender();if(view==='library')updateLibrary();debounceSave();updateUndoButtons()};
  $$('.side[data-filter]').forEach(b=>{b.setAttribute('aria-pressed',String(b.dataset.filter===activeFilter));b.onclick=()=>{activeFilter=b.dataset.filter;libraryRenderLimit=LIBRARY_PAGE_SIZE;$$('.side[data-filter]').forEach(x=>{const active=x===b;x.classList.toggle('active',active);x.setAttribute('aria-pressed',String(active))});setView('library')}});const refreshLibraryFilter=()=>{libraryRenderLimit=LIBRARY_PAGE_SIZE;updateLibrary()};$('#search').oninput=$('#filterRating').onchange=$('#sort').onchange=refreshLibraryFilter;$('#loadMoreBtn').onclick=()=>{libraryRenderLimit+=LIBRARY_PAGE_SIZE;updateLibrary()};
  $('#selectAllBtn').onclick=()=>{filteredPhotos().forEach(p=>p.selected=true);updateLibrary()};$('#deselectBtn').onclick=()=>{photos.forEach(p=>p.selected=false);updateLibrary()};$('#compareSelectedBtn').onclick=()=>runAsync('Compare selected photos',compareSelected,'The selected photos could not be compared.');$('#compareDialog').addEventListener('close',()=>{$$('#compareDialog canvas').forEach(c=>{c.width=c.height=1})});$('#batchPresetBtn').onclick=()=>{const first=photos.find(p=>p.selected);if(!first)return;batchPresetMode=true;selectPhoto(first);switchRightPanel('presets');toast('Choose a preset to apply to the selection')};$('#batchBtn').onclick=syncSelected;$('#cullBtn').onclick=()=>runAsync('Analyze catalog',analyzeCatalog,'Catalog analysis stopped because a photo could not be processed.');
  $('#mergeBtn').onclick=()=>{$('#mergeDialog').showModal()};$('#hdrMerge').onclick=e=>{e.preventDefault();$('#mergeDialog').close();runAsync('HDR merge',()=>mergeSelected('hdr'),'HDR merge failed. Check that all selected files are available.')};$('#panoMerge').onclick=e=>{e.preventDefault();$('#mergeDialog').close();runAsync('Panorama merge',()=>mergeSelected('pano'),'Panorama merge failed. Try fewer or smaller photos.')};
  $('#backupBtn').onclick=()=>runAsync('Back up catalog',async()=>{flushCatalog();const path=await window.desktop.saveCatalog(JSON.stringify({app:'Luma Darkroom',version:2,createdAt:new Date().toISOString(),photos:catalogRecords()},null,2));if(path)toast('Catalog backup saved')},'Catalog backup could not be saved.');
  $('#restoreBtn').onclick=()=>runAsync('Restore catalog',async()=>{const text=await window.desktop.openCatalog();if(!text)return;const restored=parseCatalogText(text,'backup');if(!await confirmCatalogRestore(restored))return;const preRestore=JSON.stringify({app:'Luma Darkroom',version:2,createdAt:new Date().toISOString(),reason:'Pre-restore catalog backup',photos:catalogRecords()},null,2),backupPath=await window.desktop.saveCatalog(preRestore);if(!backupPath)return toast('Restore canceled · the current catalog was not backed up');installCatalog(restored.photos);catalogDirty=true;const saved=saveCatalog();updateLibrary();if(photos[0])selectPhoto(photos[0]);else setView('library');toast(saved?`${photos.length} catalog entries restored · previous catalog backed up${restored.skipped?` · ${restored.skipped} invalid skipped`:''}`:`${photos.length} entries restored for this session, but the catalog is not saved · previous catalog backup is safe`)},'That catalog file is invalid or too large.');
  $('#saveMetadata').onclick=e=>{e.preventDefault();if(!metadataPhoto)return;metadataPhoto.rating=metadataRating;metadataPhoto.flag=$('#flagEditor').value;metadataPhoto.label=$('#labelEditor').value;metadataPhoto.tags=[...new Set($('#tagsEditor').value.split(',').map(s=>s.trim()).filter(Boolean).slice(0,100))];metadataPhoto.caption=$('#captionEditor').value.slice(0,2000);debounceSave();updateLibrary();$('#metadataDialog').close()};
  window.addEventListener('dragover',e=>{e.preventDefault();document.body.classList.add('drag')});window.addEventListener('dragleave',e=>{if(e.target===document.documentElement||e.target===document.body)document.body.classList.remove('drag')});window.addEventListener('drop',e=>{e.preventDefault();document.body.classList.remove('drag');const supported=/\.(jpe?g|png|webp|bmp|gif|tiff?|avif|hei[cf]|dng|cr[23]|nef|nrw|arw|srf|sr2|raf|rw2|orf|pef|x3f)$/i,items=[];for(const f of [...e.dataTransfer.files].filter(f=>supported.test(f.name))){try{const filePath=window.desktop.pathForFile(f);if(filePath)items.push({filePath,name:f.name,url:`local-image://load?path=${encodeURIComponent(filePath)}`})}catch(error){console.warn('[Luma] Dropped file could not be resolved',error)}}items.length?runAsync('Import dropped photos',()=>importPhotos(items),'Dropped photos could not be imported.'):toast('No supported photographs were found in that drop')});
  window.addEventListener('keydown',handleShortcut);window.addEventListener('keyup',releaseOriginalShortcut);window.addEventListener('blur',()=>{if(compare)setCompare(false)});switchRightPanel('edit');updateExportOptions();updateActionState();
}

function parseCatalogText(raw,source='catalog'){
  if(typeof raw!=='string'||raw.length>MAX_CATALOG_BYTES)throw new RangeError('Catalog is empty or too large');const data=JSON.parse(raw),list=Array.isArray(data)?data:data?.photos;if(!Array.isArray(list)||list.length>MAX_CATALOG_PHOTOS)throw new Error('Catalog photo list is invalid');
  if(!Array.isArray(data)&&data.checksum&&checksum(JSON.stringify(list))!==data.checksum)throw new Error('Catalog checksum does not match');
  const migrated=[],ids=new Set(),paths=new Set();let skipped=0;
  for(const record of list){
    try{if(!record||typeof record!=='object'||typeof record.filePath!=='string'||!record.filePath.trim()||record.filePath.length>32767)throw new Error('Invalid photo record');const pathKey=record.filePath.toLowerCase();if(paths.has(pathKey)){skipped++;continue}paths.add(pathKey);const photo=E.migratePhoto(record);if(!photo.id||ids.has(photo.id))photo.id=uid();ids.add(photo.id);migrated.push(photo)}catch(error){skipped++;console.warn(`[Luma] Skipped invalid ${source} entry`,error)}
  }
  return{photos:migrated,skipped,savedAt:num(data?.savedAt,0),generation:num(data?.generation,0),source}
}
function installCatalog(nextPhotos){
  imageLoadToken++;renderGeneration++;current=null;sourceImage.onload=sourceImage.onerror=null;sourceImage=new Image();clearPreview();clearPrefetch();undoByPhoto.clear();redoByPhoto.clear();historyLru.clear();libraryRenderLimit=LIBRARY_PAGE_SIZE;photos=nextPhotos
}
function loadCatalog(){
  const specs=[[RECOVERY_KEY,'recovery',3],[CATALOG_KEY,'catalog',4],[BACKUP_KEY,'last good backup',2],[LEGACY_KEY,'legacy catalog',1]],candidates=[];let foundRaw=false,invalid=0;
  for(const[key,label,priority]of specs){const raw=storageGet(key);if(!raw)continue;foundRaw=true;try{candidates.push({...parseCatalogText(raw,label),priority})}catch(error){invalid++;console.warn(`[Luma] Could not read ${label}`,error)}}
  if(!candidates.length){installCatalog([]);if(foundRaw)toast('The saved catalog was damaged and could not be opened. Its data was preserved for backup.');return}
  candidates.sort((a,b)=>(b.generation||b.savedAt)-(a.generation||a.savedAt)||b.priority-a.priority);const chosen=candidates[0];catalogGeneration=Math.max(0,chosen.generation||chosen.savedAt);installCatalog(chosen.photos);
  if(chosen.source!=='catalog'){catalogDirty=true;setTimeout(()=>saveCatalog(),0);toast(`Recovered ${photos.length} photos from ${chosen.source}${chosen.skipped?` · ${chosen.skipped} invalid skipped`:''}`)}else if(chosen.skipped)toast(`Catalog opened · ${chosen.skipped} invalid entr${chosen.skipped===1?'y':'ies'} skipped`)
}
function installReliabilityGuards(){
  window.addEventListener('error',event=>{if(event.error)reportFailure('Unhandled renderer error',event.error)});
  window.addEventListener('unhandledrejection',event=>{event.preventDefault();reportFailure('Unhandled async error',event.reason)});
  window.addEventListener('pagehide',flushCatalog);window.addEventListener('beforeunload',event=>{if(catalogDirty&&!saveCatalog({silent:true})){event.preventDefault();event.returnValue=''}});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')flushCatalog()});setInterval(flushCatalog,5000)
}
installReliabilityGuards();buildAdjustments();buildMaskPanel();buildPresets();bindGlobal();refreshWatermarkHistory();loadCatalog();updateLibrary();if(photos.length)selectPhoto(photos[0]);scheduleFirstRunTutorial();
